// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdfDjMtP7oHRuexPYxHkT7zZMPxIcxhGQ',
    appId: '1:159074035989:web:d1c0a224c70f55685f611c',
    messagingSenderId: '159074035989',
    projectId: 'sand-app-2127b',
    authDomain: 'sand-app-2127b.firebaseapp.com',
    storageBucket: 'sand-app-2127b.firebasestorage.app',
    measurementId: 'G-M6LHEDD5YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNENlvx7_fW1YWpo9xjeN5OzGcUgSqRA',
    appId: '1:159074035989:android:53a6eebba9efca0a5f611c',
    messagingSenderId: '159074035989',
    projectId: 'sand-app-2127b',
    storageBucket: 'sand-app-2127b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvxYtGzB2NWx8ohA6FMrXepPNBU5RcxwE',
    appId: '1:159074035989:ios:68717d7e63d3e0c75f611c',
    messagingSenderId: '159074035989',
    projectId: 'sand-app-2127b',
    storageBucket: 'sand-app-2127b.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvxYtGzB2NWx8ohA6FMrXepPNBU5RcxwE',
    appId: '1:159074035989:ios:68717d7e63d3e0c75f611c',
    messagingSenderId: '159074035989',
    projectId: 'sand-app-2127b',
    storageBucket: 'sand-app-2127b.firebasestorage.app',
    iosBundleId: 'com.example.sanad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdfDjMtP7oHRuexPYxHkT7zZMPxIcxhGQ',
    appId: '1:159074035989:web:6da45d1bf45ed1865f611c',
    messagingSenderId: '159074035989',
    projectId: 'sand-app-2127b',
    authDomain: 'sand-app-2127b.firebaseapp.com',
    storageBucket: 'sand-app-2127b.firebasestorage.app',
    measurementId: 'G-L2KR8GC4VS',
  );
}
